### ISSUE TITLE
[aws-stepfunctions] Support for ResultSelector

### ISSUE THREAD

**Issue by rodrick10** [aws/aws-step-functions-data-science-sdk-python#185] opened 2022-02-07 15:37 UTC
I have trying to find a way of using the [ResultSelector](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html) with the stef functions python sdk just like with have input_path, result_path or output_path. Seems like there is not a method to implemnet this feature. 

There is a similar issue but for the cdk project: [cdk_issue](https://github.com/aws/aws-cdk/issues/9904)

In my case I want to select the output of a LambdaStep to only consider the Payload. Something like this:
```
lambda_step= steps.compute.LambdaStep(
    "Lambda ID",
    parameters={"FunctionName": "function_name"}
    result_selector: {"output.$": "$.output.Payload"}
   )

```
This is a :rocket: Feature Request

**Comment by wong-a** [comment] 2022-02-08 01:06
Thanks for the feature request. This is a missing capability in the Python SDK. Closing as a duplicate of https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/95

There is an open PR to add it (https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/102). I'll follow up with the team to see how we can get this shipped.

**Closed as completed by wong-a** 2022-02-08 01:06 UTC
